if LE_EXPANSION_LEVEL_CURRENT <= LE_EXPANSION_CATACLYSM then return end

-- DO NOT EDIT THIS FILE; run dataminer.lua to regenerate.
local core = LibStub("AceAddon-3.0"):GetAddon("SilverDragon")

-- local ANNIVERSARY = core.conditions.CalendarEvent(1500) -- this needs to be updated each year...
local ANNIVERSARY = core.conditions.CalendarEventStartTexture(6238552)
local GREEDY = core.conditions.AuraActive(1250685) -- core.conditions.CalendarEvent(1382)

core:RegisterMobData("Events", {
    -- Anniversary
    [121818] = {name="Lord Kazzak",locations={[17]={33804860},},loot={150379,150380,150381,150382,150383,150384,150385,150386,150426,150427},quest=47461,vignette=6661,requires=ANNIVERSARY,},
    [121820] = {name="Azuregos",locations={[76]={49608260},},loot={150417,150419,150421,150422,150423,150424,150425,150428,150543,150544,150545},quest=47462,vignette=6660,requires=ANNIVERSARY,},
    [121821] = {name="Lethon",locations={[26]={63602860},},loot={150398,150399,150400,150401,150402,150407,150429,150408,150403,150412,150393,150388,150411},quest=47463,vignette=6662,requires=ANNIVERSARY,},
    [121911] = {name="Taerar",locations={[63]={93904060},},loot={150390,150392,150394,150395,150413,150414,150429,150408,150403,150412,150393,150388,150411},quest=47463,vignette=6664,requires=ANNIVERSARY,},
    [121912] = {name="Ysondre",locations={[69]={51201160},},loot={150387,150389,150391,150396,150397,150409,150429,150408,150403,150412,150393,150388,150411},quest=47463,vignette=6665,requires=ANNIVERSARY,},
    [121913] = {name="Emeriss",locations={[47]={46603940},},loot={150404,150405,150406,150410,150415,150416,150429,150408,150403,150412,150393,150388,150411},quest=47463,vignette=6663,requires=ANNIVERSARY,},
    [167749] = {name="Doomwalker",locations={[71]={58728463}},requires=ANNIVERSARY,vignette=6520,
        quest=60214, -- 85723?
        loot={
            {186469,mount=293,}, -- Illidari Doomhawk
            {208572,mount=1798,}, -- Azure Worldchiller
            {186501,toy=true,}, -- Doomwalker Trophy Stand
            186459, -- Archaic Charm of Presence
            186460, -- Anger-Spark Gloves
            186461, -- Gilded Trousers of Benediction
            186462, -- Black-Iron Battlecloak
            186463, -- Terrorweave Tunic
            186464, -- Fathom-Helm of the Deeps
            186465, -- Faceguard of the Endless Watch
            186466, -- Ethereum Nexus-Reaver
            186467, -- Barrel-Blade Longrifle
            186468, -- Talon of the Tempest
            186475, -- Hellstitched Mantle
            186481, -- Darkcrest Waistguard
            186484, -- Voidforged Greaves
            186506, -- Akama's Edge
        },
    },
    [226646] = {name="Sha of Anger",locations={[71]={33715571}},quest=84282,requires=ANNIVERSARY,vignette=6519,
        loot={},
    },
    [227257] = {name="Archavon the Stonewatcher",locations={[71]={45992897}},requires=ANNIVERSARY,vignette=6518,
        quest=84256, -- 84312?
        loot={},
    },
}, true)
