#!/usr/bin/python

import argparse
import sys

from npc import types as npctypes

blacklist = (
    50091, # untargetable Julak-Doom component
)
force_include = (
    17591, # Blood Elf Bandit
    50409, # Mysterious Camel Figurine
    50410, # Mysterious Camel Figurine (remnants)
    3868, # Blood Seeker (thought to share Aeonaxx's spawn timer)
    51236, # Aeonaxx (engaged)
    58336, # Darkmoon Rabbit
    # Lost and Found!
    64004, # Ghostly Pandaren Fisherman
    64191, # Ghostly Pandaren Craftsman
    65552, # Glinting Rapana Whelk
    64272, # Jade Warrior Statue
    64227, # Frozen Trail Packer
    #In 5.2, world bosses are no longer flagged as rare, even if they are.
    #Granted, 3 of 4 probably won't be rare. We include anyways because we always have.
    60491, # Sha of Anger
    62346, # Galleon
    69099, # Nalak
    69161, # Oondasta
)

def write_output(filename, data):
    with open(filename, 'w') as f:
        f.write("""-- DO NOT EDIT THIS FILE; run dataminer.lua to regenerate.
local core = LibStub("AceAddon-3.0"):GetAddon("SilverDragon")
local module = core:GetModule("Data")
function module:GetDefaults()
\treturn {
""")
        for id, mob in sorted(data.items()):
            if id in blacklist:
                continue
            f.write('\t\t[%d] = %s,\n' % (id, mob.to_lua()))
        f.write("""\t}
end
""")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Suck down a lot of data about rares")
    parser.add_argument('--wowhead', action='store_true', default=True)
    parser.add_argument('--no-wowhead', action='store_false', dest='wowhead')
    parser.add_argument('--wowdb', action='store_true', default=True)
    parser.add_argument('--no-wowdb', action='store_false', dest='wowdb')
    ns = parser.parse_args()

    wowdb = {}
    wowhead = {}

    if ns.wowdb:
        print("LOADING FROM wowdb")
        from npc.wowdb import WowdbNPC
        for creature_type in npctypes.values():
            print("ACQUIRING rares for category", creature_type)
            wowdb.update(WowdbNPC.query(creature_type))

        for id in force_include:
            if id not in wowdb:
                wowdb[id] = WowdbNPC(id)

    if ns.wowhead:
        print("LOADING FROM wowhead")
        from npc.wowhead import WowheadNPC
        for categoryid, c in npctypes.items():
            print("ACQUIRING rares for category", categoryid, c)
            for expansion in range(1, 6):
                print("EXPANSION", expansion)
                # run per-expansion to avoid caps on results-displayed
                wowhead.update(WowheadNPC.query(categoryid, expansion))

        for id in force_include:
            if id not in wowhead:
                wowhead[id] = WowheadNPC(id)

    defaults = wowhead
    for id, mob in wowdb.items():
        if id in defaults:
            defaults[id].extend(mob)
        else:
            defaults[id] = mob

    write_output("../Data/defaults.lua", defaults)
    print("Defaults written")
