#!/usr/bin/python

from npc import types as npctypes
from npc.wowhead import WowheadNPC

blacklist = (
    50091, # untargetable Julak-Doom component
)
force_include = (
    17591, # Blood Elf Bandit
    50409, # Mysterious Camel Figurine
    50410, # Mysterious Camel Figurine (remnants)
    3868, # Blood Seeker (thought to share Aeonaxx's spawn timer)
    51236, # Aeonaxx (engaged)
    58336, # Darkmoon Rabbit
    # Lost and Found!
    64004, # Ghostly Pandaren Fisherman
    64191, # Ghostly Pandaren Craftsman
    65552, # Glinting Rapana Whelk
    64272, # Jade Warrior Statue
    64227, # Frozen Trail Packer
    #In 5.2, world bosses are no longer flagged as rare, even if they are.
    #Granted, 3 of 4 probably won't be rare. We include anyways because we always have.
    60491, # Sha of Anger
    62346, # Galleon
    69099, # Nalak
    69161, # Oondasta
)

def write_output(filename, data):
    with open(filename, 'w') as f:
        f.write("""-- DO NOT EDIT THIS FILE; run dataminer.lua to regenerate.
local core = LibStub("AceAddon-3.0"):GetAddon("SilverDragon")
local module = core:GetModule("Data")
function module:GetDefaults()
\treturn {
""")
        for id, mob in sorted(data.items()):
            if id in blacklist:
                continue
            f.write('\t\t[%d] = %s,\n' % (id, mob.to_lua()))
        f.write("""\t}
end
""")

if __name__ == '__main__':
    defaults = {}
    npc = WowheadNPC
    for categoryid, c in npctypes.items():
        print("ACQUIRING rares for category", categoryid, c)
        for expansion in range(1, 6):
            print("EXPANSION", expansion)
            # run per-expansion to avoid caps on results-displayed
            defaults.update(npc.query(categoryid, expansion))
    for id in force_include:
        if id not in defaults:
            defaults[id] = npc(id)

    write_output("../Data/defaults.lua", defaults)
    print("Defaults written")
