name: Package Addon (Mainline)

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
    paths-ignore:
      - '.github/**'
      - 'tools/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: . --no-color -q
  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # reads history for commit changelog

      - uses: kemayo/actions-recent-changelog@v2
        if: startsWith(github.ref, 'refs/tags')
        with:
          input: CHANGELOG.md
          output: RECENT_CHANGES.md

      - name: Create Mainline Package
        uses: BigWigsMods/packager@v2
        with:
          args: -S
        env:
           CF_API_KEY: ${{ secrets.CF_API_KEY }}
           WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
           WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
           GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
